from setuptools import setup

setup(name='moodquiz',
      version='1.0.6',
      description='Imports Quizzes from Moodl software',
      url='https://github.com/tagercito/moodquiz',
      author='Damian Sastre',
      author_email='damian.sastre@gmail.com',
      license='MIT',
      python_requires='>=3',
      packages=['moodquiz'],
      install_requires=['attrs==20.3.0',
                        'beautifulsoup4==4.9.3',
                        'dashtable==1.2.9',
                        'cffi==1.14.5',
                        'configparser==5.0.2',
                        'html5lib==1.1',
                        'importlib-metadata==4.0.0',
                        'iniconfig==1.1.1',
                        'Jinja2==2.11.3',
                        'MarkupSafe==1.1.1',
                        'mechanize==0.4.5',
                        'packaging==20.9',
                        'pluggy==0.13.1',
                        'py==1.10.0',
                        'pycparser==2.20',
                        'pyparsing==2.4.7',
                        'pytest==6.2.3',
                        'six==1.15.0',
                        'soupsieve==2.2.1',
                        'toml==0.10.2',
                        'typing-extensions==3.7.4.3',
                        'webencodings==0.5.1',
                        'zipp==3.4.1'],
      entry_points={
          'console_scripts': ['mquiz=moodquiz.command_line:main'],
      },
      zip_safe=False,
      include_package_data=True)